apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:master
      - system:nodes
      rolearn: arn:aws:iam::038584427603:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::038584427603:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-HDA9ZZML30PA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-11T10:06:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2970"
  uid: 7f4c33b4-1943-4689-90da-030a75d1e3d7
