apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:masters
        rolearn: arn:aws:iam::038584427603:role/UdacityFlaskDeployCBKubectlRole
        username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::038584427603:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-10RUOTTXP047K
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T09:19:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1636"
  uid: 6cabe21d-6e95-45d9-934f-f8d77b65052c

  