apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:masters
        rolearn: arn:aws:iam::038584427603:role/UdacityFlaskDeployCBKubectlRole
        username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::038584427603:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SIOADK8N2ZT6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T12:24:36Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1641"
  uid: 749f9edd-8d85-4680-a2a3-c65570dce0a3
  